linux
linux-lts
linux-zen
linux-hardened
linux-firmware
systemd
glibc
pacman
archlinux-keyring
mkinitcpio
grub
systemd-boot
openssl
openssh
sudo
filesystem
bash
coreutils
util-linux
nvidia
nvidia-lts
nvidia-utils
mesa
NetworkManager
docker
containerd
runc
qemu-base
qemu-system-x86
virtualbox
virtualbox-host-modules-arch
